### ISSUE TITLE
Add ucdavis to Packagist and remove "repositories:ucdavis/sitefarm_seed" from composer.json

### ISSUE THREAD

**Issue by dearmond** [ucdavis/sitefarm_seed#167]
Because ucdavis/sitefarm_seed is now public, it can be added to Packagist so we don't need to declare the repo specifically.

**Comment by dearmond** [comment]
It's on Packagist:
https://packagist.org/packages/ucdavis/sitefarm_seed

Unfortunately, it says: `Language: JavaScript` I wonder if there's a way to change that.

**Comment by mrkmiller** [comment]
Looks good, I'm not sure how to change the language.

**Comment by mrkmiller** [comment]
I'm closing this since the task appears to be finished.
