### ISSUE TITLE
Fix Probo JS tests.

### ISSUE THREAD

**Issue by dearmond** [ucdavis/sitefarm_seed#191]
#188 kept failing it's behat JS tests because of a Probo issue. Fix it.

**Comment by cboyden-ucb** [comment]
One thing to look at is, updates to Behat and the Drupal extension may have caused some timing issues with Javascript tests. AfterStep functions may be affected.

**Comment by mrkmiller** [comment]
Fixed via https://github.com/ucdavis/sitefarm_seed/pull/198
